### ISSUE TITLE
CpuProfilingLoggingMode not defined in Node v12.0.x - v12.15.x

### ISSUE THREAD

**Issue by Widdershin** [hyj1991/v8-profiler-node8#27]
Hi @hyj1991.

I found out today that #25 has introduced a problem that causes v8-profiler-node8 not to load on Node v12.0 - v12.15 (works on v12.16 and up).

This is the error when loading:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v811CpuProfiler3NewEPNS_7IsolateENS_22CpuProfilingNamingModeENS_23CpuProfilingLoggingModeE
  Referenced from: /project/node_modules/v8-profiler-node8/build/binding/Release/node-v72-darwin-x64/profiler.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v811CpuProfiler3NewEPNS_7IsolateENS_22CpuProfilingNamingModeENS_23CpuProfilingLoggingModeE
  Referenced from: /project/node_modules/v8-profiler-node8/build/binding/Release/node-v72-darwin-x64/profiler.node
  Expected in: flat namespace
```

It looks like `CpuProfilingLoggingMode` was introduced in an update to `v8.h` in Node v12.16, but all Node 12 versions have the same ABI version 72.

An easy fix would be to only support this option for Node 13 onwards, but do you know of a way we might be able to fix this for Node 12?

I don't know enough about C++ to know if we can handle the presence of the symbol at runtime, or if we would need to ship separate binaries for v12.15 and v12.16, which I wouldn't expect you to have to do.

**Comment by Widdershin** [comment]
https://github.com/hyj1991/v8-profiler-node8/issues/27

**Comment by hyj1991** [comment]
In this case, maybe we can only avoid this by comparing `NODE_MAJOR_VERSION`, `NODE_MINOR_VERSION` and `NODE_PATCH_VERSION` one by one.

These have been defined at `node_version.h`, such as:

```
#define NODE_MAJOR_VERSION 12
#define NODE_MINOR_VERSION 18
#define NODE_PATCH_VERSION 1
```

**Comment by hyj1991** [comment]
Something like:

```c++
#if (NODE_MAJOR_VERSION >= 12 && NODE_MINOR_VERSION >= 16)
    v8::CpuProfilingLoggingMode loggingMode = v8::kLazyLogging;

    if (getenv("V8_PROFILER_EAGER_LOGGING")) {
      loggingMode = v8::kEagerLogging;
    }

    data->profiler = v8::CpuProfiler::New(context->GetIsolate(), v8::kDebugNaming, loggingMode);
#elif (NODE_MODULE_VERSION > 0x0039)
    data->profiler = v8::CpuProfiler::New(context->GetIsolate());
#endif
```

**Comment by hyj1991** [comment]
@Widdershin

**Comment by Widdershin** [comment]
@hyj1991 nice, that looks very promising! I was trying to find out if these variables existed but couldn't find docs.

I will try this out tomorrow and make a PR.

Does this mean we would have to ship multiple binaries for Node 12? I will have to see if `node-pre-gyp` can be configured for this case.

**Comment by hyj1991** [comment]
> Does this mean we would have to ship multiple binaries for Node 12? I will have to see if `node-pre-gyp` can be configured for this case.

Yeah, `node-pre-gyp` can only judge the `NODE_MODULE_VERSION` before installation. So users should install `v8-profiler-node8` by local compilation if we using `NODE_MAJOR_VERSION`. The pre-compiled binary can't satisfy two types of binary with one `NODE_MODULE_VERSION` at the same time.

**Comment by hyj1991** [comment]
> ~~Yeah, node-pre-gyp can only judge the NODE_MODULE_VERSION before installation. So users should install v8-profiler-node8 by local compilation if we using NODE_MAJOR_VERSION. The pre-compiled binary can't satisfy two types of binary with one NODE_MODULE_VERSION at the same time.~~

Mistaken, actually `node-pre-gyp` also supporting node version as versioning:

![image](https://user-images.githubusercontent.com/19908330/98785194-2e171d00-2437-11eb-96da-bee94016bf55.png)

It seems that just needs to change the binary configuration defined in package.json.

**Comment by Widdershin** [comment]
Okay perfect I’ll try out all the pieces together tomorrow, thanks for your
help
